version: "3"
services:
  cumbuca:
    container_name: cumbuca
    build:
      context: .
    command: /bin/sh docker_dev_start.sh
    ports:
      - "4000:4000"
    depends_on:
      - cumbuca_db
    env_file:
      - .env
    volumes:
     - ./:/app/
    networks:
      - cumbuca
     
  cumbuca_db:
    container_name: cumbuca_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - cumbuca

networks:
  cumbuca:
    name: cumbuca_network