name: Elixir CI

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_SECRET_KEY }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.0"
          otp-version: "25.0"

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Create env file
        run: |
          cp .env-sample .env

      - name: Build image
        run: make build

      - name: Run tests
        run: docker compose run --rm cumbuca mix test
      # - name: Check unused deps in lockfile
      #   run: mix deps.unlock --check-unused
      # - name: Check compile warnings
      #   run: mix compile --warnings-as-errors
      # - name: Check code formating
      #   run: mix format --check-formatted
      # - name: Check code smells
      #   run: mix credo --strict
      # - name: Check tests
      #   run: mix test --warnings-as-errors
      # - name: Check seeds consistency
      #   run: |
      #     mix ecto.create
      #     mix ecto.migrate
      #     mix run priv/repo/seeds.exs
